name: windows_system_info
description: A Flutter package for getting exclusive details of windows device.
version: 0.0.4
repository: https://github.com/Abdulazeezvp/windows_system_info

platforms:
  windows:

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  equatable: ^2.0.3

dev_dependencies:
  lints: ^3.0.0
